name: Connectivity VWAN Core CI

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terratest-workflow:
    uses: ./.github/workflows/terraform-deploy.yaml
    with:
      working_dir: ./modules/connectivity-vwan/core/test
    secrets:
      client-id: ${{secrets.CLIENT_ID}}
      subscription-id: ${{secrets.SUBSCRIPTION_ID}}
      tenant-id: ${{secrets.TENANT_ID}}
