name: Management Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-deploy:
    uses: ./.github/workflows/terraform-deploy.yaml
    with:
      working_dir: ./management
    secrets:
      client-id: ${{secrets.CLIENT_ID}}
      subscription-id: ${{secrets.SUBSCRIPTION_ID}}
      tenant-id: ${{secrets.TENANT_ID}}
